apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario
      version: green
  template:
    metadata:
      labels:
        app: inventario
        version: green
    spec:
      containers:
      - name: app
        image: ghcr.io/angymacarron2005/practica-ci-cd:latest
        ports:
        - containerPort: 3000
        # --- AGREGUEN ESTO PARA QUE LA APP SEPA QUE ES LA VERSIÓN VERDE ---
        env:
        - name: APP_COLOR
          value: "green"
        - name: APP_VERSION
          value: "v2"