apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
      - name: app
        # Atención aquí: GitHub Container Registry requiere todo en minúsculas
        image: ghcr.io/angymacarron2005/practica-ci-cd:latest 
        ports:
        - containerPort: 3000
        env:
        # Consumiendo el secreto que creó Angy (Componente extra 2)
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        # --- NUEVO COMPONENTE 3: Variable de entorno de arranque lento ---
        - name: STARTUP_DELAY_SECONDS
          value: "20"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10